import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import InternalRelativeApi from "@/types/e-internal-relative-api";
import IServerInfo from "@/types/i-server-info";

export default function Home() {
  const [clientNow, setClientNow] = useState<Date>();
  const [serverInfo, SetServerInfo] = useState<IServerInfo>();

  useEffect(() => {
    setClientNow(new Date());
    const url = InternalRelativeApi.ServerInfo;
    axios.get(url).then((response) => {
      SetServerInfo(response.data as IServerInfo);
    });
  }, []);

  const dateOnTheServer = serverInfo
    ? new Date(serverInfo.serverNowMs).toString()
    : "";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>The date on the server : {dateOnTheServer}</p>
        <p>The date on the client : {clientNow?.toString() ?? ""}</p>
        <p>Is sale day : {serverInfo?.isSalesDay.toString() ?? ""}</p>
      </main>
    </>
  );
}
