import Head from "next/head";
import { useEffect, useState } from "react";
import axios from 'axios'

export default function Home() {
  const [clientNow, setClientNow] = useState<Date>();
  const [serverNow, setServerNow] = useState<Date>();

  useEffect(() => {
    setClientNow(new Date());
    const url = '/api/server-date';
    axios.get(url)
    .then((response) => {
      console.log(response);
      
      // Use response.data to access the parsed JSON data
      setServerNow(response.data.serverNow);
    })
  },[]);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>The date on the server : {serverNow?.toLocaleString() ?? ""}</p>
        <p>The date on the client : {clientNow?.toLocaleString() ?? ""}</p>
      </main>
    </>
  );
}
